openapi: 3.0.3
info:
  title: Assistant Service API
  version: 1.0.0
  description: |
    Assistant Service provides conversational orchestration and will call other services.
    Public domain API endpoints are planned for future iterations.
servers:
  - url: http://localhost:8090
paths:
  /actuator/health:
    get:
      summary: Health check
      operationId: health
      responses:
        '200':
          description: OK
components: {}
