openapi: 3.0.3
info:
  title: Payment Service API
  version: 1.0.0
  description: |
    Payment Service processes payments in reaction to booking events from Kafka.
    This service currently does not expose public domain HTTP endpoints and works as an event consumer.
servers:
  - url: http://localhost:8082
paths:
  /actuator/health:
    get:
      summary: Health check
      operationId: health
      responses:
        '200':
          description: OK
components: {}
