openapi: 3.0.3
info:
  title: Profile Service API
  version: 1.0.0
  description: |
    Profile Service manages user profiles, preferences, and loyalty data.
    Public domain API endpoints are planned and will be added in future iterations.
servers:
  - url: http://localhost:8083
paths:
  /actuator/health:
    get:
      summary: Health check
      operationId: health
      responses:
        '200':
          description: OK
components: {}
